#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "Symlinking vim/ to ~/.vim"
ln -s $DIR/vim $HOME/.vim

echo "Symlinking vimrc to ~/.vimrc"
ln -s $DIR/vimrc $HOME/.vimrc

echo "Symlinking tmux.conf to ~/.tmux.conf"
ln -s $DIR/tmux.conf $HOME/.tmux.conf

echo "Symlinking inputrc to ~/.inputrc"
ln -s $DIR/inputrc $HOME/.inputrc

echo "Symlinking profiles.clj to ~/.lein/profiles.clj"
if [ ! -d $HOME/.lein ]; then
  mkdir $HOME/.lein
fi
if [ -f $HOME/.lein/profiles.clj ]; then
    cp $HOME/.lein/profiles.clj $HOME/.lein/profiles.clj.old
    rm $HOME/.lein/profiles.clj
fi
ln -s $DIR/lein/profiles.clj $HOME/.lein/profiles.clj


vim +PluginInstall +qall
